# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b91f959b46a92031fdb734b6a42d7d55972fe895963abe710e22a2e7e661bbee889c964f9c7e582bdbd69e55d6eaee4c3e5c5d78666742ad3a8ce333b479c98b
test:
  secret_key_base: 9b56239ff32c188766423bec7ad918416f63ce6d4183b7d80f46bbd1cbee75b051d3c71c73303ebc0bf3399b3698937dd31346dd0d9ad122f095213dc69d8afd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
